version: 2
updates:
  # # Enable version updates for npm
  # - package-ecosystem: "npm"
  #   # Look for `package.json` and `lock` files in the `root` directory
  #   directory: "/"
  #   # Check the npm registry for updates every day (weekdays)
  #   schedule:
  #     interval: "daily"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

  # # Enable version updates for Docker
  # - package-ecosystem: "docker"
  #   directory: "/meteor"
  #   schedule:
  #     interval: "weekly"
  # - package-ecosystem: "docker"
  #   directory: "/packages/mos-gateway"
  #   schedule:
  #     interval: "weekly"
  # - package-ecosystem: "docker"
  #   directory: "/packages/playout-gateway"
  #   schedule:
  #     interval: "weekly"
