openapi: '3.0.3'
info:
  title: 'Sofie User Actions API'
  description: 'The Sofie User Actions API provides paths to allow a device to control a Sofie and query health information'
  version: '0.0.1'
  license:
    name: 'MIT License'
    url: 'http://opensource.org/licenses/MIT'
servers:
  - url: http://localhost:3000
    description: Initial release of UserActions API - http - for use during development only!
tags:
  - name: userActions
    description: Provides the ability to control the Sofie application
paths:
  # user actions
  /:
    $ref: 'definitions/userActions.yaml#/resources/index'
  /activate/{rundownPlaylistId}:
    $ref: 'definitions/userActions.yaml#/resources/activate'
  /deactivate/{rundownPlaylistId}:
    $ref: 'definitions/userActions.yaml#/resources/deactivate'
  /executeAction/{rundownPlaylistId}/{actionId}:
    $ref: 'definitions/userActions.yaml#/resources/executeAction'
  /executeAdLib/{rundownPlaylistId}/{adLibId}:
    $ref: 'definitions/userActions.yaml#/resources/executeAdLib'
  /moveNextPart/{rundownPlaylistId}/{delta}:
    $ref: 'definitions/userActions.yaml#/resources/moveNextPart'
  /moveNextSegment/{rundownPlaylistId}/{delta}:
    $ref: 'definitions/userActions.yaml#/resources/moveNextSegment'
  /reloadPlaylist/{rundownPlaylistId}:
    $ref: 'definitions/userActions.yaml#/resources/reloadPlaylist'
  /resetPlaylist/{rundownPlaylistId}:
    $ref: 'definitions/userActions.yaml#/resources/resetPlaylist'
  /setNextPart/{rundownPlaylistId}/{partId}:
    $ref: 'definitions/userActions.yaml#/resources/setNextPart'
  /setNextSegment/{rundownPlaylistId}/{segmentId}:
    $ref: 'definitions/userActions.yaml#/resources/setNextSegment'
  /take/{rundownPlaylistId}:
    $ref: 'definitions/userActions.yaml#/resources/take'
