openapi: '3.0.3'
info:
  title: 'Sofie User Actions API'
  description: 'The Sofie User Actions API provides paths to allow a device to control a Sofie and query health information'
  version: '0.0.1'
  license:
    name: 'MIT License'
    url: 'http://opensource.org/licenses/MIT'
servers:
  - url: http://localhost:3000/api2
    description: Initial release of UserActions API - http - for use during development only!
tags:
  - name: userActions
    description: Provides the ability to control the Sofie application
paths:
  /:
    $ref: 'definitions/sofie.yaml#/resources/index'
  /system/blueprint:
    $ref: 'definitions/sofie.yaml#/resources/systemBlueprint'
  # peripheral devices
  /devices:
    $ref: 'definitions/devices.yaml#/resources/devices'
  /devices/{deviceId}:
    $ref: 'definitions/devices.yaml#/resources/device'
  /devices/{deviceId}/action:
    $ref: 'definitions/devices.yaml#/resources/action'
  # blueprint operations
  /blueprints:
    $ref: 'definitions/blueprints.yaml#/resources/blueprints'
  /blueprints/{blueprintId}:
    $ref: 'definitions/blueprints.yaml#/resources/blueprint'
  # playlist operations
  /playlists/{playlistId}/activate:
    $ref: 'definitions/playlists.yaml#/resources/activate'
  /playlists/{playlistId}/deactivate:
    $ref: 'definitions/playlists.yaml#/resources/deactivate'
  /playlists/{playlistId}/executeAdLib:
    $ref: 'definitions/playlists.yaml#/resources/executeAdLib'
  /playlists/{playlistId}/moveNextPart:
    $ref: 'definitions/playlists.yaml#/resources/moveNextPart'
  /playlists/{playlistId}/moveNextSegment:
    $ref: 'definitions/playlists.yaml#/resources/moveNextSegment'
  /playlists/{playlistId}/reloadPlaylist:
    $ref: 'definitions/playlists.yaml#/resources/reloadPlaylist'
  /playlists/{playlistId}/resetPlaylist:
    $ref: 'definitions/playlists.yaml#/resources/resetPlaylist'
  /playlists/{playlistId}/setNextPart:
    $ref: 'definitions/playlists.yaml#/resources/setNextPart'
  /playlists/{playlistId}/setNextSegment:
    $ref: 'definitions/playlists.yaml#/resources/setNextSegment'
  /playlists/{playlistId}/take:
    $ref: 'definitions/playlists.yaml#/resources/take'
  /playlists/{playlistId}/sourceLayer/{sourceLayerId}:
    $ref: 'definitions/playlists.yaml#/resources/sourceLayer'
  # studio operations
  /studios:
    $ref: 'definitions/studios.yaml#/resources/studios'
  /studios/{studioId}:
    $ref: 'definitions/studios.yaml#/resources/studio'
  /studios/{studioId}/switchRouteSet:
    $ref: 'definitions/studios.yaml#/resources/switchRouteSet'
  /studios/{studioId}/devices:
    $ref: 'definitions/studios.yaml#/resources/devices'
  /studios/{studioId}/devices/{deviceId}:
    $ref: 'definitions/studios.yaml#/resources/device'
  # showstyle operations
  /showstyles:
    $ref: 'definitions/showstyles.yaml#/resources/showStyleBases'
  /showstyles/{showStyleBaseId}:
    $ref: 'definitions/showstyles.yaml#/resources/showStyleBase'
  /showstyles/{showStyleBaseId}/variants:
    $ref: 'definitions/showstyles.yaml#/resources/showStyleVariants'
  /showstyles/{showStyleBaseId}/variants/{showStyleVariantId}:
    $ref: 'definitions/showstyles.yaml#/resources/showStyleVariant'
